from command import BaseCommand
from util.exceptions import FLANNException

from io.dataset import read,write
from os.path import isfile
import numpy
import time



class ComputeNearestNeighborsCommand(BaseCommand):
    
    def __init__(self):
        
        self.parser.add_option("-i", "--input-file", dest="input_file",
                  help="Input dataset file", metavar="FILE")
        self.parser.add_option("-t", "--test-file", dest="test_file",
                  help="Test dataset file (if not present, generated by sampling from the imput dataset", metavar="FILE")
        self.parser.add_option("-m", "--match-file", dest="match_file", default="match.dat",
                  help="Match file to be generated", metavar="FILE")
        self.parser.add_option("-n", "--nn", type="int", default=1,
                  help="How many NN to compute (default 1)")
        self.parser.add_option("-c", "--count", type="int", default=1000,
                  help="How many features to sample in test set if needed. (default: 1000)")

    def execute(self):
        pass